name: Jailsmp
version: '${project.version}'
main: me.bardiagameowner.com.jailsmp.Jailsmp
api-version: 1.17
authors: [ bardiagameowner ]
description: desc

commands:
  jail:
    description: This Command is for Jail
